package qrcodex

import (
	"image"
	"image/color"
	"math"

	"github.com/minlib/go-util/imagex"
	"github.com/skip2/go-qrcode"
)

// Qrcode generates a basic QR code image without default border.
// It disables the library's default border to reduce redundant whitespace.
// Parameters:
//   - content: The data to be encoded in the QR code (e.g., URL, text)
//   - level: Error correction level (Low, Medium, High, Highest)
//   - size: Width and height of the generated QR code image in pixels
//
// Returns:
//   - image.Image: The generated QR code image
//   - error: Non-nil if QR code generation fails
func Qrcode(content string, level qrcode.RecoveryLevel, size int) (image.Image, error) {
	qrCode, err := qrcode.New(content, level)
	if err != nil {
		return nil, err
	}
	// Disable library's default border to reduce redundant blank space
	qrCode.DisableBorder = true
	qrcodeImage := qrCode.Image(size)
	return qrcodeImage, nil
}

// QrcodeWithBorder generates a QR code image with a custom white border (quiet zone).
// It adds a white border to the base QR code (generated by Qrcode) to meet QR code quiet zone requirements.
// Border width is calculated as 5% of the target size (minimum 2px to ensure scannability).
// Parameters:
//   - content: The data to be encoded in the QR code
//   - level: Error correction level (Low, Medium, High, Highest)
//   - size: Total width and height of the final image (including border) in pixels
//
// Returns:
//   - image.Image: QR code image with white border
//   - error: Non-nil if QR code generation or border addition fails
func QrcodeWithBorder(content string, level qrcode.RecoveryLevel, size int) (image.Image, error) {
	// Calculate border width: 5% of size (minimum 2px to meet QR code quiet zone standard)
	borderWidth := int(math.Max(float64(size)*0.05, 2))
	// Generate base QR code with size adjusted for border (subtract 2*borderWidth from total size)
	baseImage, err := Qrcode(content, level, size-borderWidth*2)
	if err != nil {
		return nil, err
	}
	// Add white border (RGB 255,255,255) with rectangular mode (circular=false)
	qrcodeImage := imagex.AddBorder(baseImage, borderWidth, color.RGBA{R: 255, G: 255, B: 255, A: 255}, false)
	return qrcodeImage, nil
}
